import { useEffect, useMemo, useRef, useState } from 'react'
import type { CSSProperties } from 'react'
import { api } from '../api'
import Layout from '../components/Layout'
import type { Overview } from '../types'

type View = 'split' | 'week'
type Item = { id:string; sourceId:number; source:'event'|'task'; date:string; title:string; detail:string; startTime:string; endTime:string; tone:string; kind:string; subjectStyle?:CSSProperties }
type Drag = { item:Item; mode:'move'|'resize'; startY:number; start:number; end:number }
type EventForm = { title:string; event_type:string; start_date:string; end_date:string; start_time:string; end_time:string; repeat_weekly:boolean }
const WEEKDAYS=['일','월','화','수','목','금','토'], HOURS=Array.from({length:19},(_,i)=>i+6), DAY_START=360, DAY_END=1440, PX=32
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const minutes=(v:string)=>{const [h,m]=v.split(':').map(Number);return h*60+m}, clock=(v:number)=>`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`
const mondayOf=(value:Date)=>{const d=new Date(value),day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));d.setHours(0,0,0,0);return d}
export const subjectStyle=(index:number)=>({ '--subject-bg':`hsl(${(index*137.508)%360} 58% 91%)`,'--subject-ink':`hsl(${(index*137.508)%360} 48% 30%)`,'--subject-accent':`hsl(${(index*137.508)%360} 48% 52%)`} as CSSProperties)
const emptyForm=():EventForm=>({title:'',event_type:'CLASS',start_date:dateKey(new Date()),end_date:dateKey(new Date()),start_time:'09:00',end_time:'10:00',repeat_weekly:false})

export default function CalendarPage(){
 const [data,setData]=useState<Overview>({events:[],exams:[]}),[cursor,setCursor]=useState(new Date()),[view,setView]=useState<View>('split'),[selectedDate,setSelectedDate]=useState(dateKey(new Date()))
 const [showForm,setShowForm]=useState(false),[error,setError]=useState(''),[form,setForm]=useState<EventForm>(emptyForm),[split,setSplit]=useState(()=>Number(localStorage.getItem('calendarSplitPercent'))||60)
 const [preview,setPreview]=useState<{id:string;start:number;end:number}|null>(null),dragRef=useRef<Drag|null>(null),splitRef=useRef<HTMLDivElement|null>(null),resizing=useRef(false)
 const load=async()=>{try{setData(await api.overview());setError('')}catch{setError('백엔드에 연결할 수 없습니다.')}}
 useEffect(()=>{void load()},[])
 useEffect(()=>{const move=(e:PointerEvent)=>{if(!resizing.current||!splitRef.current)return;const b=splitRef.current.getBoundingClientRect();setSplit(Math.max(45,Math.min(75,(e.clientX-b.left)/b.width*100)))};const stop=()=>{resizing.current=false};window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop)}},[])
 useEffect(()=>localStorage.setItem('calendarSplitPercent',String(split)),[split])
 const items=useMemo<Item[]>(()=>{const subjects=[...new Set(data.exams.map(e=>e.subject))].sort(),styleFor=(subject:string)=>subjectStyle(subjects.indexOf(subject));return [
  ...data.events.map(x=>({id:`event-${x.id}`,sourceId:x.id,source:'event' as const,date:x.starts_at.slice(0,10),title:x.title,detail:'고정 일정',startTime:x.starts_at.slice(11,16),endTime:x.ends_at.slice(11,16),tone:'event',kind:'일정'})),
  ...data.exams.flatMap(e=>e.tasks.map(x=>({id:`task-${x.id}`,sourceId:x.id,source:'task' as const,date:x.study_date,title:e.subject,detail:`${x.pass_number}회독 · ${x.scope_start}–${x.scope_end} ${e.scope_unit}`,startTime:x.suggested_start_time,endTime:x.suggested_end_time,tone:`${x.status.toLowerCase()} subject-color`,kind:'공부',subjectStyle:styleFor(e.subject)}))),
  ...data.exams.map(e=>({id:`exam-${e.id}`,sourceId:e.id,source:'event' as const,date:e.exam_date,title:`${e.subject} 시험`,detail:`목표 ${e.target_passes}회독`,startTime:e.exam_time,endTime:clock(Math.min(1439,minutes(e.exam_time)+60)),tone:'exam subject-color',kind:'시험',subjectStyle:styleFor(e.subject)}))]},[data])
 const monthDays=useMemo(()=>{const f=new Date(cursor.getFullYear(),cursor.getMonth(),1),s=new Date(f.getFullYear(),f.getMonth(),1-f.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return d})},[cursor])
 const weekDays=useMemo(()=>{const s=mondayOf(cursor);return Array.from({length:7},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return d})},[cursor]),dayItems=useMemo(()=>items.filter(x=>x.date===selectedDate).sort((a,b)=>a.startTime.localeCompare(b.startTime)),[items,selectedDate])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{if(form.repeat_weekly)await api.createRecurringEvent({title:form.title,event_type:form.event_type,start_date:form.start_date,end_date:form.end_date,start_time:form.start_time,end_time:form.end_time});else await api.createEvent({title:form.title,event_type:form.event_type,starts_at:`${form.start_date}T${form.start_time}:00`,ends_at:`${form.start_date}T${form.end_time}:00`});setForm(emptyForm());setShowForm(false);await load()}catch(reason){setError((reason as Error).message)}}
 const openDay=(d:string)=>{setSelectedDate(d);setCursor(new Date(`${d}T00:00:00`))},movePeriod=(n:number)=>{const d=new Date(cursor);view==='split'?d.setMonth(d.getMonth()+n,1):d.setDate(d.getDate()+n*7);setCursor(d)}
 const begin=(e:React.PointerEvent,item:Item,mode:'move'|'resize')=>{if(item.kind==='시험')return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);const start=minutes(item.startTime);dragRef.current={item,mode,startY:e.clientY,start,end:minutes(item.endTime)};setPreview({id:item.id,start,end:minutes(item.endTime)})}
 const drag=(e:React.PointerEvent)=>{const d=dragRef.current;if(!d)return;const delta=Math.round(((e.clientY-d.startY)/PX*60)/15)*15,duration=d.end-d.start;if(d.mode==='move'){const start=Math.max(DAY_START,Math.min(DAY_END-duration,d.start+delta));setPreview({id:d.item.id,start,end:start+duration})}else setPreview({id:d.item.id,start:d.start,end:Math.max(d.start+30,Math.min(DAY_END,d.end+delta))})}
 const endDrag=async()=>{const d=dragRef.current,p=preview;dragRef.current=null;setPreview(null);if(!d||!p||(p.start===d.start&&p.end===d.end))return;try{d.item.source==='task'?await api.updateTaskTime(d.item.sourceId,{suggested_start_time:clock(p.start),suggested_end_time:clock(p.end)}):await api.updateEventTime(d.item.sourceId,{starts_at:`${d.item.date}T${clock(p.start)}:00`,ends_at:`${d.item.date}T${clock(p.end)}:00`});await load()}catch(reason){setError((reason as Error).message);await load()}}
 const block=(item:Item)=>{const shown=preview?.id===item.id?preview:{start:minutes(item.startTime),end:minutes(item.endTime)},start=Math.max(DAY_START,shown.start),end=Math.min(DAY_END,shown.end);return <article className={`time-block ${item.tone} ${item.kind==='시험'?'locked':''}`} key={item.id} style={{...item.subjectStyle,top:`${(start-DAY_START)/60*PX}px`,height:`${Math.max(24,(end-start)/60*PX)}px`}} onPointerDown={e=>begin(e,item,'move')} onPointerMove={drag} onPointerUp={()=>void endDrag()}><span>{clock(start)}–{clock(end)} · {item.kind}</span><strong>{item.title}</strong><small>{item.detail}</small>{item.kind!=='시험'&&<i className="resize-handle" onPointerDown={e=>{e.stopPropagation();begin(e,item,'resize')}} aria-label="길이 조절"/>}</article>}
 const title=view==='split'?`${cursor.getFullYear()}년 ${cursor.getMonth()+1}월`:`${dateKey(weekDays[0])} – ${dateKey(weekDays[6])}`
 return <Layout>
  <header className="calendar-header"><div><span className="kicker">INTEGRATED CALENDAR</span><h1>나의 시간표</h1></div><div className="calendar-actions"><div className="view-switch"><button className={view==='split'?'active':''} onClick={()=>setView('split')}>월 + 일</button><button className={view==='week'?'active':''} onClick={()=>setView('week')}>주간</button></div><button className="btn btn-primary" onClick={()=>setShowForm(v=>!v)}>+ 고정 일정</button></div></header>
  {error&&<div className="notice error">{error}</div>}
  {showForm&&<form className="event-form" onSubmit={submit}><label>일정명<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>종류<select value={form.event_type} onChange={e=>setForm({...form,event_type:e.target.value})}><option value="CLASS">수업</option><option value="WORK">아르바이트</option><option value="APPOINTMENT">약속</option><option value="OTHER">기타</option></select></label><label>시작일<input required type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value,end_date:form.end_date<e.target.value?e.target.value:form.end_date})}/></label>{form.repeat_weekly&&<label>반복 종료일<input required min={form.start_date} type="date" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></label>}<label>시작 시간<input required type="time" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/></label><label>종료 시간<input required type="time" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/></label><label className="repeat-toggle"><input type="checkbox" checked={form.repeat_weekly} onChange={e=>setForm({...form,repeat_weekly:e.target.checked})}/><span><b>매주 반복</b><small>같은 요일과 시간에 반복합니다.</small></span></label><button className="btn btn-primary">{form.repeat_weekly?'반복 일정 저장':'일정 저장'}</button></form>}
  <section className="calendar-shell"><div className="calendar-toolbar"><button onClick={()=>movePeriod(-1)}>‹</button><h2>{title}</h2><button onClick={()=>movePeriod(1)}>›</button><button className="today-button" onClick={()=>{const t=new Date();setCursor(t);setSelectedDate(dateKey(t))}}>오늘</button></div>
   {view==='split'&&<div ref={splitRef} className="month-day-split" style={{gridTemplateColumns:`minmax(0,${split}fr) 12px minmax(360px,${100-split}fr)`}}><div className="month-calendar"><div className="weekday-row">{WEEKDAYS.map(d=><span key={d}>{d}</span>)}</div><div className="month-grid">{monthDays.map(day=>{const key=dateKey(day),entries=items.filter(x=>x.date===key);return <button className={`month-day ${day.getMonth()!==cursor.getMonth()?'outside':''} ${key===dateKey(new Date())?'today':''} ${key===selectedDate?'selected':''}`} key={key} onClick={()=>openDay(key)}><span className="day-number">{day.getDate()}</span><div className="month-events">{entries.slice(0,2).map(x=><span className={`month-event ${x.tone}`} style={x.subjectStyle} key={x.id}>{x.startTime} {x.title}</span>)}{entries.length>2&&<small>+{entries.length-2}</small>}</div></button>})}</div></div><button type="button" className="split-resizer" aria-label="월간과 일간 캘린더 너비 조절" onPointerDown={e=>{e.preventDefault();resizing.current=true}}><i/></button><div className="split-day-calendar"><div className="split-day-header"><div><span>{new Date(`${selectedDate}T00:00:00`).toLocaleDateString('ko-KR',{weekday:'long'})}</span><strong>{new Date(`${selectedDate}T00:00:00`).getDate()}</strong></div><p>블록 이동 · 아래 손잡이로 길이 조절</p></div><div className="timeline"><div className="time-axis">{HOURS.map(h=><span key={h}>{String(h).padStart(2,'0')}:00</span>)}</div><div className="time-track">{HOURS.map(h=><i className="hour-line" style={{top:`${(h-6)*PX}px`}} key={h}/>)}{dayItems.map(block)}{dayItems.length===0&&<div className="day-empty">등록된 일정이 없습니다.</div>}</div></div></div></div>}
   {view==='week'&&<div className="week-calendar"><div className="week-columns">{weekDays.map(day=>{const key=dateKey(day),entries=items.filter(x=>x.date===key);return <button key={key} className={key===dateKey(new Date())?'today':''} onClick={()=>openDay(key)}><span>{WEEKDAYS[day.getDay()]}</span><strong>{day.getDate()}</strong><div>{entries.slice(0,6).map(x=><i className={x.tone} style={x.subjectStyle} key={x.id}>{x.startTime}<b>{x.title}</b></i>)}</div></button>})}</div></div>}
  </section>
 </Layout>
}
